### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by PeterUstinox**
typo

### CODE REVIEW

**Comment by petrepatrasc** [comment]
Thanks @PeterUstinox, appreciate it!

**Comment by petrepatrasc** [comment]
It seems @coveralls is acting up a bit here.

**Comment by PeterUstinox** [comment]
wtf is this?

**Comment by petrepatrasc** [comment]
@PeterUstinox Apparently @coveralls is migrating to a new hosting provider, which is making everything kind of weird right now in their GH hook. Anyway, I've triggered an update, and coverage is back up to 98% where it should be :-)

**Pull request merged**
